"""
Script to add Phase 4 — Presentation Dashboard cells to the V2 GNN notebook.
Run once, then delete this script.
"""
import json

NB_PATH = r"AI_3D_Stress_Validator_V2_GNN.ipynb"

with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

# ── New cells to append ─────────────────────────────────────────────────────

new_cells = [
    # ── Phase 4 header ──
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Phase 4 — Presentation Dashboard\n",
            "\n",
            "Polished, **presentation-ready** visualizations that make the project's \n",
            "value immediately obvious — ideal for portfolio, reports, or demos."
        ]
    },

    # ── 4.1 Dataset Overview Dashboard ──
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 4.1  Dataset Overview Dashboard\n",
            "#      Stress distribution + class balance + per-load-case ranges\n",
            "\n",
            "import matplotlib.pyplot as plt\n",
            "import matplotlib.gridspec as gridspec\n",
            "import numpy as np\n",
            "\n",
            "# --- Premium dark theme ---\n",
            "plt.rcParams.update({\n",
            "    'figure.facecolor': '#0D1117',\n",
            "    'axes.facecolor':   '#161B22',\n",
            "    'axes.edgecolor':   '#30363D',\n",
            "    'axes.labelcolor':  '#C9D1D9',\n",
            "    'text.color':       '#C9D1D9',\n",
            "    'xtick.color':      '#8B949E',\n",
            "    'ytick.color':      '#8B949E',\n",
            "    'grid.color':       '#21262D',\n",
            "    'grid.alpha':       0.6,\n",
            "    'font.family':      'sans-serif',\n",
            "    'font.size':        10,\n",
            "})\n",
            "\n",
            "# Color palette\n",
            "PASS_COLOR = '#3FB950'   # GitHub green\n",
            "FAIL_COLOR = '#F85149'   # GitHub red\n",
            "ACCENT     = '#58A6FF'   # GitHub blue\n",
            "GOLD       = '#D29922'   # GitHub gold\n",
            "\n",
            "fig = plt.figure(figsize=(20, 6))\n",
            "gs = gridspec.GridSpec(1, 3, width_ratios=[2, 1, 2], wspace=0.35)\n",
            "\n",
            "# --- Panel 1: Stress Distribution with PASS/FAIL shading ---\n",
            "ax1 = fig.add_subplot(gs[0])\n",
            "stress_vals = df['max_stress_all'].values\n",
            "bins = np.linspace(stress_vals.min(), stress_vals.max(), 40)\n",
            "\n",
            "ax1.hist(stress_vals[stress_vals < threshold], bins=bins,\n",
            "         color=PASS_COLOR, alpha=0.85, label='PASS', edgecolor='none')\n",
            "ax1.hist(stress_vals[stress_vals >= threshold], bins=bins,\n",
            "         color=FAIL_COLOR, alpha=0.85, label='FAIL', edgecolor='none')\n",
            "ax1.axvline(threshold, color=GOLD, linewidth=2.5, linestyle='--',\n",
            "            label=f'Threshold: {threshold:.1f} MPa', zorder=5)\n",
            "\n",
            "ax1.set_xlabel('Max Stress (MPa)', fontsize=12, fontweight='bold')\n",
            "ax1.set_ylabel('Number of Parts', fontsize=12, fontweight='bold')\n",
            "ax1.set_title('Stress Distribution', fontsize=14, fontweight='bold', pad=12)\n",
            "ax1.legend(fontsize=10, loc='upper right',\n",
            "           facecolor='#161B22', edgecolor='#30363D')\n",
            "ax1.grid(axis='y')\n",
            "\n",
            "# --- Panel 2: Class Balance Donut Chart ---\n",
            "ax2 = fig.add_subplot(gs[1])\n",
            "n_pass = int(len(df) - df['label'].sum())\n",
            "n_fail = int(df['label'].sum())\n",
            "wedges, texts, autotexts = ax2.pie(\n",
            "    [n_pass, n_fail],\n",
            "    labels=['PASS', 'FAIL'],\n",
            "    colors=[PASS_COLOR, FAIL_COLOR],\n",
            "    autopct='%1.0f%%',\n",
            "    startangle=90,\n",
            "    pctdistance=0.78,\n",
            "    wedgeprops=dict(width=0.45, edgecolor='#0D1117', linewidth=2),\n",
            "    textprops=dict(fontsize=12, fontweight='bold'),\n",
            ")\n",
            "for at in autotexts:\n",
            "    at.set_color('#FFFFFF')\n",
            "    at.set_fontweight('bold')\n",
            "ax2.set_title('Class Balance', fontsize=14, fontweight='bold', pad=12)\n",
            "# Center text with total count\n",
            "ax2.text(0, 0, f'{len(df)}\\nparts', ha='center', va='center',\n",
            "         fontsize=16, fontweight='bold', color='#C9D1D9')\n",
            "\n",
            "# --- Panel 3: Per-Load-Case Box Plot ---\n",
            "ax3 = fig.add_subplot(gs[2])\n",
            "box_data = [df[col].values for col in STRESS_COLS]\n",
            "short_names = [c.replace('stress_', '').replace('_mpa', '')\n",
            "               .replace('_', ' ').title() for c in STRESS_COLS]\n",
            "\n",
            "bp = ax3.boxplot(box_data, labels=short_names, patch_artist=True,\n",
            "                 medianprops=dict(color=GOLD, linewidth=2),\n",
            "                 whiskerprops=dict(color='#8B949E'),\n",
            "                 capprops=dict(color='#8B949E'),\n",
            "                 flierprops=dict(marker='o', markerfacecolor=FAIL_COLOR,\n",
            "                                 markersize=4, alpha=0.6))\n",
            "\n",
            "# Gradient colors for boxes\n",
            "cmap = plt.cm.get_cmap('cool', len(STRESS_COLS))\n",
            "for i, patch in enumerate(bp['boxes']):\n",
            "    patch.set_facecolor(cmap(i))\n",
            "    patch.set_alpha(0.75)\n",
            "    patch.set_edgecolor('#30363D')\n",
            "\n",
            "ax3.axhline(threshold, color=FAIL_COLOR, linewidth=1.5, linestyle=':',\n",
            "            alpha=0.7, label=f'Fail Threshold')\n",
            "ax3.set_ylabel('Stress (MPa)', fontsize=12, fontweight='bold')\n",
            "ax3.set_title('Stress by Load Case', fontsize=14, fontweight='bold', pad=12)\n",
            "ax3.tick_params(axis='x', rotation=25)\n",
            "ax3.legend(fontsize=9, facecolor='#161B22', edgecolor='#30363D')\n",
            "ax3.grid(axis='y')\n",
            "\n",
            "fig.suptitle('\\U0001f4ca  Dataset Overview \\u2014 AI 3D Stress Validator V2',\n",
            "             fontsize=18, fontweight='bold', y=1.02, color='#F0F6FC')\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    },

    # ── 4.2 Model Performance Report Card ──
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 4.2  Model Performance Report Card\n",
            "#      Confusion matrix + prediction scatter + residual distribution\n",
            "\n",
            "import matplotlib.pyplot as plt\n",
            "import matplotlib.gridspec as gridspec\n",
            "import numpy as np\n",
            "from sklearn.metrics import confusion_matrix, r2_score, mean_absolute_error\n",
            "\n",
            "fig = plt.figure(figsize=(20, 7))\n",
            "gs = gridspec.GridSpec(1, 3, width_ratios=[1, 1.4, 1], wspace=0.3)\n",
            "\n",
            "# Recompute metrics for display\n",
            "_mae = mean_absolute_error(all_stress_true, all_stress_pred)\n",
            "_r2  = r2_score(all_stress_true, all_stress_pred)\n",
            "\n",
            "# --- Panel 1: Confusion Matrix ---\n",
            "ax1 = fig.add_subplot(gs[0])\n",
            "cm = confusion_matrix(all_label_true, all_label_pred)\n",
            "cm_labels = np.array([['True\\nPASS', 'False\\nFAIL'],\n",
            "                      ['False\\nPASS', 'True\\nFAIL']])\n",
            "\n",
            "# Build color-coded matrix\n",
            "im = ax1.imshow(cm, cmap='RdYlGn_r', aspect='auto', alpha=0.85)\n",
            "for i in range(2):\n",
            "    for j in range(2):\n",
            "        label_text = f'{cm_labels[i,j]}\\n\\n{cm[i,j]}'\n",
            "        ax1.text(j, i, label_text, ha='center', va='center',\n",
            "                 fontsize=13, fontweight='bold',\n",
            "                 color='white' if cm[i,j] > cm.max()/2 else '#C9D1D9')\n",
            "\n",
            "ax1.set_xticks([0, 1])\n",
            "ax1.set_yticks([0, 1])\n",
            "ax1.set_xticklabels(['PASS', 'FAIL'], fontsize=12, fontweight='bold')\n",
            "ax1.set_yticklabels(['PASS', 'FAIL'], fontsize=12, fontweight='bold')\n",
            "ax1.set_xlabel('Predicted', fontsize=13, fontweight='bold')\n",
            "ax1.set_ylabel('Actual', fontsize=13, fontweight='bold')\n",
            "ax1.set_title('Confusion Matrix', fontsize=14, fontweight='bold', pad=12)\n",
            "\n",
            "# Accuracy annotation\n",
            "_acc = np.trace(cm) / cm.sum()\n",
            "ax1.text(0.5, -0.18, f'Accuracy: {_acc*100:.1f}%',\n",
            "         transform=ax1.transAxes, ha='center', fontsize=13,\n",
            "         fontweight='bold', color=PASS_COLOR if _acc > 0.8 else GOLD)\n",
            "\n",
            "# --- Panel 2: Predicted vs True Stress ---\n",
            "ax2 = fig.add_subplot(gs[1])\n",
            "\n",
            "# Error bands\n",
            "lims = [min(all_stress_true.min(), all_stress_pred.min()) * 0.9,\n",
            "        max(all_stress_true.max(), all_stress_pred.max()) * 1.1]\n",
            "band_x = np.linspace(lims[0], lims[1], 100)\n",
            "ax2.fill_between(band_x, band_x * 0.8, band_x * 1.2,\n",
            "                 alpha=0.08, color=ACCENT, label='\\u00b120% band')\n",
            "ax2.fill_between(band_x, band_x * 0.9, band_x * 1.1,\n",
            "                 alpha=0.12, color=ACCENT, label='\\u00b110% band')\n",
            "\n",
            "# Scatter points colored by error magnitude\n",
            "errors = np.abs(all_stress_pred - all_stress_true)\n",
            "sc = ax2.scatter(all_stress_true, all_stress_pred,\n",
            "                 c=errors, cmap='YlOrRd', s=60, alpha=0.85,\n",
            "                 edgecolors='#30363D', linewidth=0.5, zorder=5)\n",
            "plt.colorbar(sc, ax=ax2, shrink=0.8, label='Abs Error (MPa)')\n",
            "\n",
            "# Perfect prediction line\n",
            "ax2.plot(lims, lims, '--', color=PASS_COLOR, linewidth=2,\n",
            "         label='Perfect', zorder=4)\n",
            "\n",
            "ax2.set_xlim(lims)\n",
            "ax2.set_ylim(lims)\n",
            "ax2.set_xlabel('True Stress (MPa)', fontsize=12, fontweight='bold')\n",
            "ax2.set_ylabel('Predicted Stress (MPa)', fontsize=12, fontweight='bold')\n",
            "ax2.set_title(f'Prediction Accuracy   R\\u00b2 = {_r2:.3f}',\n",
            "              fontsize=14, fontweight='bold', pad=12)\n",
            "ax2.legend(fontsize=9, loc='upper left',\n",
            "           facecolor='#161B22', edgecolor='#30363D')\n",
            "ax2.grid(alpha=0.3)\n",
            "ax2.set_aspect('equal')\n",
            "\n",
            "# --- Panel 3: Residual Distribution ---\n",
            "ax3 = fig.add_subplot(gs[2])\n",
            "residuals = all_stress_pred - all_stress_true\n",
            "ax3.hist(residuals, bins=25, color=ACCENT, alpha=0.8,\n",
            "         edgecolor='#0D1117', linewidth=0.8)\n",
            "ax3.axvline(0, color=PASS_COLOR, linewidth=2, linestyle='--',\n",
            "            label='Zero Error')\n",
            "ax3.axvline(residuals.mean(), color=GOLD, linewidth=2,\n",
            "            label=f'Mean: {residuals.mean():.2f}')\n",
            "\n",
            "ax3.set_xlabel('Prediction Error (MPa)', fontsize=12, fontweight='bold')\n",
            "ax3.set_ylabel('Count', fontsize=12, fontweight='bold')\n",
            "ax3.set_title('Error Distribution', fontsize=14, fontweight='bold', pad=12)\n",
            "ax3.legend(fontsize=9, facecolor='#161B22', edgecolor='#30363D')\n",
            "ax3.grid(axis='y')\n",
            "\n",
            "# Summary annotation box\n",
            "stats_text = (f'MAE  : {_mae:.2f} MPa\\n'\n",
            "              f'R\\u00b2   : {_r2:.4f}\\n'\n",
            "              f'Acc  : {_acc*100:.1f}%\\n'\n",
            "              f'Bias : {residuals.mean():+.2f}')\n",
            "ax3.text(0.97, 0.97, stats_text, transform=ax3.transAxes,\n",
            "         va='top', ha='right', fontsize=10, family='monospace',\n",
            "         bbox=dict(boxstyle='round,pad=0.5', facecolor='#21262D',\n",
            "                   edgecolor='#30363D', alpha=0.9))\n",
            "\n",
            "fig.suptitle('\\U0001f9e0  GNN Model Performance \\u2014 Report Card',\n",
            "             fontsize=18, fontweight='bold', y=1.02, color='#F0F6FC')\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    },

    # ── 4.3 3D Mesh Comparison — PASS vs FAIL ──
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 4.3  3D Mesh Comparison \\u2014 PASS vs FAIL\n",
            "#      Side-by-side risk heatmap on actual mesh geometry\n",
            "\n",
            "import matplotlib.pyplot as plt\n",
            "import numpy as np\n",
            "import torch\n",
            "\n",
            "# Find one PASS and one FAIL sample from the validation set\n",
            "pass_sample = None\n",
            "fail_sample = None\n",
            "for d in val_data:\n",
            "    if d.y.item() == 0 and pass_sample is None:\n",
            "        pass_sample = d\n",
            "    elif d.y.item() == 1 and fail_sample is None:\n",
            "        fail_sample = d\n",
            "    if pass_sample is not None and fail_sample is not None:\n",
            "        break\n",
            "\n",
            "# Fallback if only one class in val set\n",
            "if pass_sample is None:\n",
            "    pass_sample = val_data[0]\n",
            "if fail_sample is None:\n",
            "    fail_sample = val_data[-1]\n",
            "\n",
            "fig = plt.figure(figsize=(20, 8))\n",
            "\n",
            "model.eval()\n",
            "for idx, (sample, title_tag) in enumerate([\n",
            "    (pass_sample, 'PASS'), (fail_sample, 'FAIL')\n",
            "]):\n",
            "    with torch.no_grad():\n",
            "        out = model(sample.to(DEVICE))\n",
            "    node_risk = out['node_risk'].cpu().numpy().flatten()\n",
            "    stress_pred = out['stress'].cpu().item()\n",
            "    pos = sample.pos.numpy()\n",
            "\n",
            "    # --- Full view ---\n",
            "    ax = fig.add_subplot(1, 4, idx * 2 + 1, projection='3d')\n",
            "    sc = ax.scatter(pos[:, 0], pos[:, 1], pos[:, 2],\n",
            "                    c=node_risk, cmap='inferno', s=6, alpha=0.85,\n",
            "                    vmin=0, vmax=1)\n",
            "    verdict_color = PASS_COLOR if title_tag == 'PASS' else FAIL_COLOR\n",
            "    ax.set_title(f'{title_tag}  \\u2022  {stress_pred:.1f} MPa\\n'\n",
            "                 f'{sample.item_name}',\n",
            "                 fontsize=13, fontweight='bold', color=verdict_color, pad=10)\n",
            "    ax.set_xlabel('X', fontsize=8)\n",
            "    ax.set_ylabel('Y', fontsize=8)\n",
            "    ax.set_zlabel('Z', fontsize=8)\n",
            "    ax.tick_params(labelsize=7)\n",
            "\n",
            "    # --- Zoomed danger zone ---\n",
            "    ax_z = fig.add_subplot(1, 4, idx * 2 + 2, projection='3d')\n",
            "    top_k = max(1, int(len(node_risk) * 0.15))  # top 15% risk nodes\n",
            "    high_risk_idx = np.argsort(node_risk)[-top_k:]\n",
            "    hr_pos = pos[high_risk_idx]\n",
            "    hr_risk = node_risk[high_risk_idx]\n",
            "\n",
            "    sc2 = ax_z.scatter(hr_pos[:, 0], hr_pos[:, 1], hr_pos[:, 2],\n",
            "                       c=hr_risk, cmap='hot', s=18, alpha=0.95,\n",
            "                       vmin=0, vmax=1, edgecolors='#30363D', linewidth=0.3)\n",
            "\n",
            "    # Background: show the full shape faintly\n",
            "    ax_z.scatter(pos[:, 0], pos[:, 1], pos[:, 2],\n",
            "                c='#21262D', s=1, alpha=0.2)\n",
            "\n",
            "    risk_center = hr_pos.mean(axis=0)\n",
            "    ax_z.scatter(*risk_center, c='cyan', s=120, marker='X',\n",
            "                zorder=10, edgecolors='white', linewidth=1)\n",
            "\n",
            "    ax_z.set_title(f'Danger Zone  \\u2022  Top 15% Risk\\n'\n",
            "                   f'Max Risk: {node_risk.max():.3f}',\n",
            "                   fontsize=11, fontweight='bold', color=GOLD, pad=10)\n",
            "    ax_z.set_xlabel('X', fontsize=8)\n",
            "    ax_z.set_ylabel('Y', fontsize=8)\n",
            "    ax_z.set_zlabel('Z', fontsize=8)\n",
            "    ax_z.tick_params(labelsize=7)\n",
            "\n",
            "# Shared colorbar\n",
            "cbar_ax = fig.add_axes([0.93, 0.15, 0.015, 0.65])\n",
            "cbar = fig.colorbar(sc, cax=cbar_ax)\n",
            "cbar.set_label('Node Risk Score', fontsize=11, fontweight='bold')\n",
            "\n",
            "fig.suptitle('\\U0001f52c  3D Structural Comparison \\u2014 PASS vs FAIL Part',\n",
            "             fontsize=18, fontweight='bold', y=1.01, color='#F0F6FC')\n",
            "plt.tight_layout(rect=[0, 0, 0.92, 0.96])\n",
            "plt.show()"
        ]
    },

    # ── 4.4 Pipeline Summary — Final Report ──
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 4.4  Pipeline Summary \\u2014 Final Report\n",
            "\n",
            "from IPython.display import display, HTML\n",
            "\n",
            "# Gather stats\n",
            "n_parts = len(graph_list)\n",
            "avg_nodes = int(np.mean([g.num_nodes for g in graph_list]))\n",
            "avg_edges = int(np.mean([g.edge_index.shape[1] for g in graph_list]))\n",
            "total_params = sum(p.numel() for p in model.parameters())\n",
            "\n",
            "html = f\"\"\"\n",
            "<div style=\"\n",
            "    background: linear-gradient(135deg, #0D1117 0%, #161B22 50%, #1A1E2E 100%);\n",
            "    border: 1px solid #30363D;\n",
            "    border-radius: 16px;\n",
            "    padding: 32px 40px;\n",
            "    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;\n",
            "    color: #C9D1D9;\n",
            "    max-width: 820px;\n",
            "    margin: 20px auto;\n",
            "    box-shadow: 0 8px 32px rgba(0,0,0,0.4);\n",
            "\">\n",
            "\n",
            "  <h2 style=\"text-align:center; color:#F0F6FC; margin:0 0 6px 0;\n",
            "             font-size:24px; letter-spacing:0.5px;\">\n",
            "    \\U0001f9e0 AI 3D Stress Validator \\u2014 V2 GNN Summary\n",
            "  </h2>\n",
            "  <p style=\"text-align:center; color:#8B949E; margin:0 0 28px 0; font-size:13px;\">\n",
            "    Physics-Informed Structural Validation via Graph Neural Networks\n",
            "  </p>\n",
            "\n",
            "  <!-- Pipeline Arrow -->\n",
            "  <div style=\"display:flex; align-items:center; justify-content:center;\n",
            "              gap:8px; margin:0 0 28px 0; flex-wrap:wrap;\">\n",
            "    <span style=\"background:#21262D; padding:10px 18px; border-radius:10px;\n",
            "                 border:1px solid #30363D; font-weight:600; font-size:14px;\">\\U0001f4d0 STL Mesh</span>\n",
            "    <span style=\"color:#58A6FF; font-size:22px;\">\\u2192</span>\n",
            "    <span style=\"background:#21262D; padding:10px 18px; border-radius:10px;\n",
            "                 border:1px solid #30363D; font-weight:600; font-size:14px;\">\\U0001f578\\ufe0f Graph (V,E)</span>\n",
            "    <span style=\"color:#58A6FF; font-size:22px;\">\\u2192</span>\n",
            "    <span style=\"background:#21262D; padding:10px 18px; border-radius:10px;\n",
            "                 border:1px solid #30363D; font-weight:600; font-size:14px;\">\\U0001f9e0 GNN</span>\n",
            "    <span style=\"color:#58A6FF; font-size:22px;\">\\u2192</span>\n",
            "    <span style=\"background:#21262D; padding:10px 18px; border-radius:10px;\n",
            "                 border:1px solid #30363D; font-weight:600; font-size:14px;\">\\U0001f3af Risk Map</span>\n",
            "  </div>\n",
            "\n",
            "  <!-- Stats Grid -->\n",
            "  <div style=\"display:grid; grid-template-columns:repeat(4,1fr); gap:14px;\n",
            "              margin-bottom:24px;\">\n",
            "    <div style=\"background:#21262D; padding:16px; border-radius:10px;\n",
            "               border:1px solid #30363D; text-align:center;\">\n",
            "      <div style=\"font-size:26px; font-weight:700; color:#58A6FF;\">{n_parts}</div>\n",
            "      <div style=\"font-size:11px; color:#8B949E; margin-top:4px;\">Parts Trained</div>\n",
            "    </div>\n",
            "    <div style=\"background:#21262D; padding:16px; border-radius:10px;\n",
            "               border:1px solid #30363D; text-align:center;\">\n",
            "      <div style=\"font-size:26px; font-weight:700; color:#D29922;\">{total_params:,}</div>\n",
            "      <div style=\"font-size:11px; color:#8B949E; margin-top:4px;\">Parameters</div>\n",
            "    </div>\n",
            "    <div style=\"background:#21262D; padding:16px; border-radius:10px;\n",
            "               border:1px solid #30363D; text-align:center;\">\n",
            "      <div style=\"font-size:26px; font-weight:700; color:#3FB950;\">{_r2:.3f}</div>\n",
            "      <div style=\"font-size:11px; color:#8B949E; margin-top:4px;\">R\\u00b2 Score</div>\n",
            "    </div>\n",
            "    <div style=\"background:#21262D; padding:16px; border-radius:10px;\n",
            "               border:1px solid #30363D; text-align:center;\">\n",
            "      <div style=\"font-size:26px; font-weight:700; color:#F85149;\">{_mae:.1f}</div>\n",
            "      <div style=\"font-size:11px; color:#8B949E; margin-top:4px;\">MAE (MPa)</div>\n",
            "    </div>\n",
            "  </div>\n",
            "\n",
            "  <!-- Details -->\n",
            "  <div style=\"display:grid; grid-template-columns:1fr 1fr; gap:14px;\n",
            "              margin-bottom:24px;\">\n",
            "    <div style=\"background:#21262D; padding:16px 20px; border-radius:10px;\n",
            "               border:1px solid #30363D;\">\n",
            "      <div style=\"font-size:13px; font-weight:700; color:#58A6FF;\n",
            "                  margin-bottom:10px;\">\\U0001f4d0 Graph Stats (avg)</div>\n",
            "      <div style=\"font-size:12px; line-height:1.8;\">\n",
            "        Nodes per graph: <b>{avg_nodes:,}</b><br>\n",
            "        Edges per graph: <b>{avg_edges:,}</b><br>\n",
            "        Node features: <b>6D</b> (xyz + normals)<br>\n",
            "        Edge features: <b>1D</b> (distance)\n",
            "      </div>\n",
            "    </div>\n",
            "    <div style=\"background:#21262D; padding:16px 20px; border-radius:10px;\n",
            "               border:1px solid #30363D;\">\n",
            "      <div style=\"font-size:13px; font-weight:700; color:#D29922;\n",
            "                  margin-bottom:10px;\">\\U0001f9e0 Model Config</div>\n",
            "      <div style=\"font-size:12px; line-height:1.8;\">\n",
            "        Architecture: <b>StressGNN ({NUM_GNN_LAYERS}-layer GCN)</b><br>\n",
            "        Hidden dim: <b>{HIDDEN_CHANNELS}</b><br>\n",
            "        Stress columns: <b>{len(STRESS_COLS)}</b> load cases<br>\n",
            "        Best epoch: <b>{best_epoch}</b>\n",
            "      </div>\n",
            "    </div>\n",
            "  </div>\n",
            "\n",
            "  <!-- Verdict -->\n",
            "  <div style=\"background: linear-gradient(90deg, #238636 0%, #2EA043 100%);\n",
            "              padding:14px 24px; border-radius:10px; text-align:center;\">\n",
            "    <span style=\"font-size:15px; font-weight:700; color:white;\n",
            "                 letter-spacing:0.5px;\">\n",
            "      \\u2705  Model trained and validated \\u2014 ready for inference on new STL files\n",
            "    </span>\n",
            "  </div>\n",
            "\n",
            "</div>\n",
            "\"\"\"\n",
            "\n",
            "display(HTML(html))"
        ]
    },
]

nb["cells"].extend(new_cells)

with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=4, ensure_ascii=False)

print(f"Done! Added {len(new_cells)} cells (Phase 4) to {NB_PATH}")
print("   You can now delete this script: add_phase4_cells.py")
